### ISSUE TITLE
switch to headless chrome (with selenium inside spider) as scraper alternative for reactive websites

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/OpenScraper#11]
**roadmap :**

- [x] add choice 'parse_reactive' in spider config : front and spider's datamodel
- [x] add selenium + chromedriver on server / local
- [x] write switchers in master_spider
  - [x] switch for 'next_page'
  - [x] switch for 'follow_link' 
- [x] redirect data to items 
- [x] test locally with reactive and non-reactive websites
- [x] add to prod
  - [x] install chromedriver on server
  - [x] update dependencies on server
  - [x] make some test in prod mode
- [x] add info install chromedriver dans doc install
- [x] merge selenium branch with master

**Comment by JulienParis** [comment]
roadmap : 
- [ ] add choice 'parse_reactive' in spider config : front and spider's datamodel
- [ ] add selenium + chromedriver on server / local
- [ ] write switchers in master_spider
- [ ] redirect data to items

**Comment by JulienParis** [comment]
exemple de site problématique : 
- https://www.unccas.org/-banque-d-experiences- : bonton 'next page' n'est pas activé avec `.click()`de Selenium
